---
settings:
  name: NetApp Console setup and administration
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  release_notes_autogen:
    release_notes_repo: console-relnotes
  rss_page: whats-new.html
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: NetApp Console管理
    url: "/index.html"
  - title: 發行說明
    entries:
    - title: 什麼是新的
      url: "/whats-new.html"
    - title: 已知限制
      url: "/reference-limitations.html"
  - title: 開始
    entries:
    - title: 學習基礎知識
      entries:
      - title: 了解NetApp Console
        url: "/concept-overview.html"
      - title: 了解NetApp Console部署模式
        url: "/concept-modes.html"
      - title: NetApp支援帳戶
        url: "/task-adding-nss-accounts.html"
      - title: 了解控制台代理
        url: "/concept-agents.html"
      - title: 身分和存取管理
        url: "/concept-identity-and-access-management.html"
    - title: 開始使用 NetApp Console（SaaS）
      entries:
      - title: 入門工作流程
        url: "/task-quick-start-standard-mode.html"
      - title: 準備NetApp Console的網路訪問
        url: "/reference-networking-saas-console.html"
      - title: 註冊NetApp Console
        url: "/task-sign-up-saas.html"
      - title: 使用NetApp Console助手
        url: "/task-console-assistant.html"
    - title: NetApp Console入門（受限模式）
      entries:
      - title: 受限模式入門工作流程
        url: "/task-quick-start-restricted-mode.html"
      - title: 準備進行受限的NetApp Console部署
        url: "/task-prepare-restricted-mode.html"
      - title: 以受限模式部署NetApp Console
        url: "/task-install-restricted-mode.html"
      - title: 訂閱NetApp Intelligent Services
        url: "/task-subscribe-restricted-mode.html"
      - title: 接下來可以做什麼
        url: "/reference-whats-next-restricted-mode.html"
    - title: 開始使用 NetApp Console（私人模式）
      entries:
      - title: 私有模式入門工作流程
        url: "/task-quick-start-private-mode.html"
      - title: 準備部署
        url: "/task-prepare-private-mode.html"
      - title: 部署控制台代理
        url: "/task-install-private-mode.html"
      - title: 接下來可以做什麼
        url: "/reference-whats-next-private-mode.html"
  - title: 使用NetApp Console
    entries:
    - title: 登入NetApp Console
      url: "/task-logging-in.html"
    - title: 查看與不同 Console 代理程式相關聯的系統
      url: "/task-manage-multiple-agents.html"
    - title: 查看NetApp Console主頁上的指標
      url: "/task-dashboard.html"
    - title: 管理您的NetApp Console使用者設定
      url: "/task-user-settings.html"
  - title: 管理和監測
    entries:
    - title: NetApp支援帳戶
      entries:
      - title: 管理 NSS 憑證
        url: "/task-adding-nss-accounts.html"
      - title: 管理與您的NetApp Console登入關聯的憑證
        url: "/task-manage-user-credentials.html"
    - title: 控制台代理
      entries:
      - title: 了解控制台代理
        url: "/concept-agents.html"
      - title: 部署控制台代理
        entries:
        - title: 選擇 Console 代理程式部署方法
          url: "/concept-agent-install-options.html"
        - title: AWS
          entries:
          - title: AWS 的 Console 代理程式安裝選項
            url: "/concept-install-aws.html"
          - title: 透過NetApp Console在 AWS 中建立控制台代理
            url: "/task-install-agent-aws-console.html"
          - title: 從 AWS Marketplace 在 AWS 中建立 Console 代理程式
            url: "/task-install-agent-aws-marketplace.html"
          - title: 在 AWS 中手動安裝 Console 代理程式
            url: "/task-install-agent-aws-manual.html"
        - title: Azure
          entries:
          - title: Azure 的 Console 代理程式安裝選項
            url: "/concept-install-azure.html"
          - title: 從NetApp Console在 Azure 中建立控制台代理
            url: "/task-install-agent-azure-console.html"
          - title: 從 Azure 市場在 Azure 中建立 Console 代理程式
            url: "/task-install-agent-azure-marketplace.html"
          - title: 在 Azure 中手動安裝 Console 代理程式
            url: "/task-install-agent-azure-manual.html"
        - title: Google雲
          entries:
          - title: Google Cloud 的 Console 代理程式安裝選項
            url: "/concept-install-google.html"
          - title: 透過NetApp Console在 Google Cloud 中建立控制台代理
            url: "/task-install-agent-google-console-gcloud.html"
          - title: 從 Google Cloud 建立 Google Cloud 的 Console 代理程式
            url: "/task-install-agent-google-gcloud.html"
          - title: 在 Google Cloud 手動安裝 Console 代理程式
            url: "/task-install-agent-google-manual.html"
        - title: 在本地安裝代理
          entries:
          - title: 在本機手動安裝控制台代理
            url: "/task-install-agent-on-prem.html"
          - title: 在 vCenter 中本機安裝 Console 代理程式
            url: "/task-install-agent-on-prem-ova.html"
          - title: 本機控制台代理的連接埠
            url: "/reference-ports-on-prem.html"
      - title: 維護控制台代理
        entries:
        - title: 維護手動安裝的 Console 代理程式
          entries:
          - title: 維護 VCenter 安裝的代理
            url: "/task-agent-vm-config.html"
          - title: 維護手動安裝的代理程式
            url: "/task-maintain-agents.html"
        - title: 更新代理程式定址和 URI
          url: "/task-update-agent-addressing.html"
        - title: 安裝 CA 簽章憑證以存取 Web 控制台
          url: "/task-installing-https-cert.html"
        - title: 配置控制台代理以使用代理伺服器
          url: "/task-configuring-proxy.html"
        - title: 控制台代理故障排除
          url: "/task-troubleshoot-agent.html"
        - title: 升級控制台代理
          url: "/task-upgrade-agent.html"
        - title: 解除安裝並刪除控制台代理
          url: "/task-uninstall-agent.html"
      - title: 管理雲端提供者憑證
        entries:
        - title: AWS
          entries:
          - title: 了解憑證和權限
            url: "/concept-accounts-aws.html"
          - title: 管理憑證和訂閱
            url: "/task-adding-aws-accounts.html"
        - title: Azure
          entries:
          - title: 了解憑證和權限
            url: "/concept-accounts-azure.html"
          - title: 管理憑證和訂閱
            url: "/task-adding-azure-accounts.html"
        - title: Google雲
          entries:
          - title: 了解項目和權限
            url: "/concept-accounts-gcp.html"
          - title: 管理憑證和訂閱
            url: "/task-adding-gcp-accounts.html"
    - title: 身分和存取管理
      entries:
      - title: 了解如何管理身份和訪問
        url: "/concept-identity-and-access-management.html"
      - title: 開始使用身分和存取權限
        url: "/task-iam-get-started.html"
      - title: 關於身分識別與存取管理的常見問題
        url: "/faq-iam-netapp-console.html"
      - title: 設定您的控制台組織
        entries:
        - title: 建立資料夾和項目
          url: "/task-iam-manage-folders-projects.html"
        - title: 將資源關聯到資料夾和項目
          url: "/task-iam-manage-resources.html"
        - title: 將控制台代理程式與其他資料夾和項目關聯
          url: "/task-iam-associate-agents.html"
      - title: 將使用者新增至您的控制台組織
        entries:
        - title: 新增使用者、服務帳戶和聯合群組
          url: "/task-iam-manage-members-permissions.html"
      - title: 管理使用者存取權限和安全
        entries:
        - title: 了解基於角色的存取控制 (RBAC)
          url: "/concept-iam-rbac.html"
        - title: 管理用戶訪問
          url: "/task-iam-manage-roles.html"
        - title: 管理成員安全
          url: "/task-iam-user-security.html"
      - title: NetApp Console存取角色
        entries:
        - title: NetApp Console存取角色
          url: "/reference-iam-predefined-roles.html"
        - title: 平台角色
          url: "/reference-iam-platform-roles.html"
        - title: 應用程式角色
          entries:
          - title: Google Cloud NetApp Volumes角色
            url: "/reference-iam-gcnv-roles.html"
          - title: Keystone角色
            url: "/reference-iam-keystone-roles.html"
          - title: 營運支援分析師
            url: "/reference-iam-analyst-roles.html"
        - title: 儲存角色
          url: "/reference-iam-storage-roles.html"
        - title: 數據服務角色
          entries:
          - title: 備份和還原角色
            url: "/reference-iam-backup-rec-roles.html"
          - title: 災難復原角色
            url: "/reference-iam-disaster-rec-roles.html"
          - title: 勒索軟體抵禦能力角色
            url: "/reference-iam-ransomware-roles.html"
      - title: 身分和存取 API
        entries:
        - title: 組織和專案 ID
          url: "/task-iam-rename-organization.html"
        - title: 身分識別和存取管理 API 參考
          url: https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html
    - title: 安全與合規
      entries:
      - title: 身分聯合
        entries:
        - title: 了解身分聯合
          url: "/concept-federation.html"
        - title: 網域驗證
          entries:
          - title: 驗證您的域名
            url: "/task-federation-verify-domain.html"
        - title: 配置聯合
          entries:
          - title: 與 Active Directory 聯合驗證服務 (AD FS) 提供者聯合
            url: "/task-federation-adfs.html"
          - title: 與 Microsoft Entra ID 提供者聯合
            url: "/task-federation-entra-id.html"
          - title: 與 PingFederate 聯合
            url: "/task-federation-ping.html"
          - title: 與 SAML 身分提供者聯合
            url: "/task-federation-saml.html"
        - title: 管理聯盟
          entries:
          - title: 管理您的聯合連接
            url: "/task-federation-manage.html"
          - title: 匯入現有的聯合連接
            url: "/task-federation-import.html"
      - title: 在NetApp Console中強制執行ONTAP權限
        url: "/task-ontap-access-agent.html"
      - title: 為組織啟用唯讀模式
        url: "/task-enable-read-only-mode.html"
      - title: NetApp Console的 SOC-2 合規性
        url: https://www.netapp.com/company/trust-center/compliance/soc-2/
    - title: 管理組織夥伴關係
      entries:
      - title: 了解組織合作關係
        url: "/concept-org-partnerships.html"
      - title: 建立組織夥伴關係
        url: "/task-partnerships-create.html"
      - title: 管理合作組織的成員
        url: "/task-partnerships-assign-users.html"
      - title: 管理合作組織的資源訪問
        url: "/task-partnerships-resource-access.html"
      - title: 在組織夥伴關係中工作
        url: "/task-partnerships-work.html"
    - title: 監控NetApp Console操作
      url: "/task-monitor-cm-operations.html"
    - title: Licenses and subscriptions
      url: https://docs.netapp.com/us-en/console-licenses-subscriptions/index.html
  - title: 參考
    entries:
    - title: 代理維護控制台
      entries:
      - title: 配置檢查
        url: "/reference-agent-maint-console-config-checker.html"
      - title: 透明代理
        url: "/reference-agent-maint-console-proxy.html"
    - title: 雲端提供者代理權限和網路要求
      entries:
      - title: 權限摘要
        url: "/reference-permissions.html"
      - title: AWS 代理權限和安全性規則
        entries:
        - title: 控制台代理的 AWS 權限
          url: "/reference-permissions-aws.html"
        - title: AWS 中的控制台代理程式安全性群組規則
          url: "/reference-ports-aws.html"
      - title: Azure 權限和所需安全性規則
        entries:
        - title: 控制台代理程式的 Azure 權限
          url: "/reference-permissions-azure.html"
        - title: Azure 中的控制台代理程式安全性群組規則
          url: "/reference-ports-azure.html"
      - title: Google Cloud 權限和所需的防火牆規則
        entries:
        - title: 控制台代理的 Google Cloud 權限
          url: "/reference-permissions-gcp.html"
        - title: Google Cloud 中的控制台代理防火牆規則
          url: "/reference-ports-gcp.html"
    - title: 控制台網路存取（舊版）
      url: "/reference-networking-saas-console-previous.html"
    - title: 要求在 EC2 執行個體上使用 IMDSv2
      url: "/task-require-imdsv2.html"
    - title: 預設代理程式配置
      url: "/reference-agent-default-config.html"
  - title: 知識和支持
    entries:
    - title: 註冊以獲得支持
      url: "/task-support-registration.html"
    - title: 獲取協助
      url: "/task-get-help.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: NetApp Console
  repo: console-family
