---
sidebar: sidebar 
permalink: reference-iam-data-classification.html 
keywords: role-based access control, IAM roles, access delegation, data classification, cloud data sense, compliance admin, classification viewer 
summary: NetApp Data Classification 支援兩種角色來管理對資產的讀取與寫入存取。 
---
= NetApp Data Classification 角色於 NetApp Console 中
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Data Classification 支援身分與存取管理角色，讓你能夠靈活地為使用者指派符合其在組織內需完成任務的特定角色。你如何指派角色，取決於你自己的業務與儲存管理實務。

Data Classification 支援兩種角色：

* 合規管理員
* 分類檢視器




[[compliance-admin]]
== 合規管理員

Compliance admin 角色僅在組織層級運作，以管理 NetApp Data Classification 資源的存取。如果使用者的職責低於 Organization admin，則必須擁有 Compliance admin 角色才能安裝 NetApp Data Classification。


IMPORTANT: 合規管理員角色並非獨立角色。擁有合規管理員角色的使用者也必須至少關聯一個link:reference-iam-platform-roles.html["平台角色"]。


NOTE: Compliance admin 已在 1.54 版新增至 Data Classification。如果您在此版本之前部署了 Data Classification，且平台角色的存取權限低於 organization admin，則 Compliance admin 角色會自動與使用者帳戶建立關聯。



[[classification-viewer]]
== 分類檢視器

Classification viewer 專為需要存取 Data Classification 掃描結果但無需存取組態資源的使用者而設計。具有 Classification viewer 角色的使用者可以檢視對應和完整掃描的結果，以評估儲存空間節省或潛在資料風險的領域。具有 Classification viewer 角色的使用者還可以為其有存取權限的資源產生報告。這些使用者無法啟用或停用磁碟區、儲存區或資料庫架構的掃描。



[[more-information]]
== 更多資訊

* link:https://docs.netapp.com/us-en/data-services-data-classification/concept-classification.html["瞭解 NetApp Data Classification"^]

