---
sidebar: sidebar 
permalink: reference-agent-maint-console-config-checker.html 
keywords: agent maintenance console, agent troubleshooting, network connectivity validation, agent validation, hardware requirements, deployment readiness, operational compliance, installation troubleshooting 
summary: 您可以使用控制台代理維護控制台來驗證控制台代理程式的安裝和配置。 
---
= 在 NetApp Console 中使用維護主控台驗證 Console 代理程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用控制台代理維護控制台來驗證控制台代理程式的安裝和配置。



== 存取代理維護控制台

您可以從 Console 代理主機存取維護主控台。瀏覽至下列目錄：

[source, cli]
----
/opt/application/netapp/service-manager-2/agent-maint-console
----


== 配置檢查器驗證

這 `config-checker validate`此命令可讓您驗證控制台代理的配置。



=== 參數

`--services <comma-separated list of services to validate>` - *必需的* -

[role="quick-margin-para"]
選擇一或多項服務進行驗證。有效的服務名稱為：

* `PLATFORM` 它會驗證與所需 Console 端點的網路連線能力，以及 Console 代理程式所需的連接埠是否已開啟。


`--validationTypes <comma-separated list of validation types to run>` --*必填*-- 請選擇一種或多種驗證類型進行執行。有效的驗證類型包括：

* `NETWORK`驗證與所需 NetApp Console 端點的網路連線。
* `HARDWARE` 這會驗證代理主機是否符合 NetApp Console 代理的最低硬體需求。
+

NOTE: 在安裝期間、NetApp 會檢查代理主機至少有 80% 的可用磁碟空間總計、其中包括 48 GB 在 `/opt`和 32 GB 在 `/var`（總計 80 GB）。安裝後、需要至少 20% 的磁碟總計保持可用、其中包括 12 GB 在 `/opt`和 8 GB 在 `/var`（總計 20 GB）。



`--proxy <url>` - *選修的* -

[role="quick-margin-para"]
指定用於驗證的代理伺服器 URL。如果您的代理程式配置為使用代理伺服器，則此項目為必填項。

`--certs <paths>` - *選修的* -

[role="quick-margin-para"]
指定用於驗證的一個或多個證書檔案的路徑。證書文件必須為PEM格式。多個路徑之間以逗號分隔。如果您的代理程式使用自訂證書，則此參數為必填項。



=== 配置檢查器驗證範例

以下範例包括驗證網路連線、所需連接埠和硬體需求，以及使用 Proxy 伺服器和自訂憑證的不同組合。

.網路連線能力和硬體需求的驗證：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE
----
.使用代理伺服器作為代理時的驗證：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --proxy http://proxy.company.com:8080
----
.使用證書驗證代理程式：
[source, cli]
----
./agent-maint-console config-checker validate --services PLATFORM --validationTypes NETWORK,HARDWARE --certs /path/to/cert1.pem,/path/to/cert2.pem
----


=== 查看任何命令的幫助

若要查看任何命令的協助，請附加 `--help`到命令。例如，要查看 `proxy add`命令，使用以下命令：

[source, cli]
----
./agent-maint-console proxy add --help
----