---
sidebar: sidebar 
permalink: reference-networking-saas-console.html 
keywords: networking, urls, endpoints, web browser, console, network, set up networking, bluexp 
summary: NetApp Console、 NetApp Console代理和NetApp資料服務需要出站網路存取以及聯繫必要端點的能力。 
---
= NetApp Console 的網路存取
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console、 NetApp Console代理和NetApp資料服務需要出站網路存取以及聯繫必要端點的能力。

您需要為以下操作設定網路存取：

* 以軟體即服務 (SaaS) 形式存取NetApp Console的計算機
* 您在本機或雲端安裝的控制台代理程式。控制台代理。



NOTE: 在 4.0.0 中， NetApp減少了控制台和控制台代理程式所需的網路端點，增強了安全性並簡化了部署。重要的是，4.0.0 版本之前的所有部署都將繼續全面支援。雖然先前的端點仍然可供現有代理程式使用，但NetApp強烈建議在確認代理程式升級成功後將防火牆規則更新到目前端點。link:reference-networking-saas-console-previous.html["了解如何更新您的端點清單。"]



== NetApp Console和控制台代理程式聯繫的端點

您部署的每個代理程式和存取NetApp Console的每台電腦都必須連接到下面列出的端點。

部署在您的雲端提供者中的控制台代理程式需要存取該雲端提供者各自的端點。

[cols="2*"]
|===
| 端點 | 目的 


| \ https://mysupport.netapp.com | 取得許可資訊並向NetApp支援發送AutoSupport訊息。 


| \ https://signin.b2c.netapp.com | 更新NetApp支援網站 (NSS) 憑證或將新的 NSS 憑證新增至NetApp Console。 


| \ https://support.netapp.com | 取得許可資訊並向NetApp支援發送AutoSupport訊息以及接收Cloud Volumes ONTAP的軟體更新。 


| \https://api.bluexp.netapp.com \https://netapp-cloud-account.auth0.com \https://netapp-cloud-account.us.auth0.com \https://console.netapp.com \https://components.console.netapp.com \https://cdn.auth0.com | 在NetApp Console中提供功能和服務。 


 a| 
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io
 a| 
取得控制台代理升級的影像。

* 當您部署新代理程式時，驗證檢查會測試與目前端點的連線。如果你使用link:reference-networking-saas-console-previous.html["先前的端點"]，驗證檢查失敗。為了避免此失敗，請跳過驗證檢查。
+
儘管先前的端點仍然受支持，但NetApp建議盡快將防火牆規則更新至目前端點。link:reference-networking-saas-console-previous.html#update-endpoint-list["了解如何更新終端節點列表"] 。

* 當您更新到防火牆中的目前端點時，您現有的代理程式將繼續運作。




 a| 
\https://occmclientinfragov.azurecr.us.io \https://bluexpinfraprod.azurecr.io
 a| 
取得控制台代理升級的影像。

* 當您部署新代理程式時，驗證檢查會測試與目前端點的連線。如果你使用link:reference-networking-saas-console-previous.html["先前的端點"]，驗證檢查失敗。為了避免此失敗，請跳過驗證檢查。
+
儘管先前的端點仍然受支持，但NetApp建議盡快將防火牆規則更新至目前端點。link:reference-networking-saas-console-previous.html#update-endpoint-list["了解如何更新終端節點列表"] 。

* 當您更新到防火牆中的目前端點時，您現有的代理程式將繼續運作。


^1^ NetApp建議在防火牆中允許選項 1 端點，因為它們更安全，而不允許選項 2 端點。請注意有關這些端點的以下事項：

+ * 從控制台代理 3.9.47 版本開始，系統支援選項 1 中列出的端點。控制台代理的先前版本不支援向後相容。 * 控制台代理程式首先聯絡選項 2 中的端點。如果這些端點不可訪問，它會自動聯繫選項 1 中的端點。 * 如果您將控制台代理程式與NetApp Backup and Recovery或 Ransomware Resilience 一起使用，則系統不支援選項 1 端點。允許選項 2 端點並不允許選項 1。



| 如果 Console 代理程式位於 AWS Government 區域：\https://*.blob.core.windows.net \https://cloudmanagerinfraprod.azurecr.io | 當 Console 代理程式安裝在 AWS Government 區域中時，取得用於 Console 代理程式升級的映像。 


| 如果 Console 代理程式位於 Azure Government 區域：\https://*.blob.core.windows.net \https://occmclientinfragov.azurecr.us | 在 Azure Government 區域中安裝 Console 代理程式時，取得用於 Console 代理程式升級的映像。 


 a| 
如果 Console 代理位於商業區域或主權區域，您可以從兩組端點中進行選擇：

* 選項 1（推薦）^1^
+
\ https://bluexpinfraprod.eastus2.data.azurecr.io \ https://bluexpinfraprod.azurecr.io

* 選項 2
+
\https://*.blob.core.windows.net \ https://cloudmanagerinfraprod.azurecr.io


| 當 Console agent 安裝在商業區域或主權區域時，取得 Console agent 升級所需的映像檔。[cols=3*,options="header,autowidth"] 
|===
|*適用於 3.9.55 及以下版本的端點* | *適用於 4.0.0 及以上版本的端點* | *用途*

a| * \https://support.netapp.com * \https://mysupport.netapp.com a| * \https://mysupport.netapp.com * \https://signin.b2c.netapp.com * \https://support.netapp.com a| 用於授權和聯絡 NetApp 支援。a| * \https://*.api.bluexp.netapp.com * \https://api.bluexp.netapp.com * \https://*.cloudmanager.cloud.netapp.com * \https://cloudmanager.cloud.netapp.com * \https://netapp-cloud-account.auth0.com * \https://netapp-cloud-account.us.auth0.com * \https://console.netapp.com * \https://*.console.netapp.com a| * \https://api.bluexp.netapp.com * \https://netapp-cloud-account.auth0.com * \https://netapp-cloud-account.us.auth0.com * \https://console.netapp.com * \https://components.console.netapp.com * \https://cdn.auth0.com a| 用於日常作業。a| * \https://*.blob.core.windows.net * \https://cloudmanagerinfraprod.azurecr.io a| * \https://bluexpinfraprod.eastus2.data.azurecr.io * \https://bluexpinfraprod.azurecr.io | 用於取得 Console 代理程式升級的映像。

|===
|===


== 雲端提供者端點聯繫了控制台代理

如果控制台代理程式部署在您的雲端提供者中，則它們必須能夠存取其他端點。

在安裝控制台代理之前設定雲端提供者網路端點存取。

* link:task-install-agent-aws-console.html#networking-aws-agent["為控制台代理程式設定 AWS 網路訪問"]
* link:task-install-agent-azure-console.html#networking-azure-agent["為控制台代理程式設定 Azure 網路訪問"]
* link:task-install-agent-google-console-gcloud.html#networking-gcp-agent["為控制台代理設定 Google Cloud 網路訪問"]




== 控制台代理聯繫的資料服務端點

一些NetApp資料服務以及Cloud Volumes ONTAP要求代理程式具有額外的出站網路存取權限。



=== Cloud Volumes ONTAP的端點

* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-aws.html#outbound-internet-access-for-cloud-volumes-ontap-nodes["AWS 中的Cloud Volumes ONTAP端點"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-azure.html["Azure 中的Cloud Volumes ONTAP端點"]
* link:https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/reference-networking-gcp.html#outbound-internet-access["Google Cloud 中Cloud Volumes ONTAP的端點"]




=== 工作負載端點

控制台代理程式必須能夠存取以下NetApp工作負載端點。

[cols="2*"]
|===
| 端點 | 目的 


 a| 
https://api.workloads.netapp.com
 a| 
基於 Web 的控制台透過與 Workload Factory API 互動來管理和操作基於ONTAP 的FSx 工作負載。

|===