---
sidebar: sidebar 
permalink: reference-iam-platform-roles.html 
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management, bluexp 
summary: 為使用者指派平台角色，以授予管理NetApp控制台、指派角色、新增使用者、建立控制台代理程式和管理聯合的權限。 
---
= NetApp控制台平台存取角色
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
為使用者指派平台角色，以授予管理NetApp控制台、指派角色、新增使用者、建立控制台代理程式和管理聯合的權限。

.大型跨國組織的組織角色範例
XYZ 公司按地區（北美、歐洲和亞太地區）組織資料儲存訪問，從而提供區域控制和集中監督。

XYZ 公司控制台中的*組織管理員*為每個區域建立一個初始組織和單獨的資料夾。每個區域的*資料夾或專案管理員*在該區域的資料夾中組織專案（及相關資源）。

具有「資料夾或專案管理員」角色的區域管理員透過新增資源和使用者來主動管理他們的資料夾。這些區域管理員還可以新增、刪除或重新命名他們管理的資料夾和項目。*組織管理員*繼承任何新資源的權限，保持整個組織的儲存使用情況的可見性。

在同一個組織內，一名使用者被指派了*共同管理員*角色來管理該組織與其企業 IdP 的聯合。該使用者可以新增或刪除聯合組織，但不能管理組織內的使用者或資源。*組織管理員*為使用者指派*共同檢視者*角色，以檢查聯合狀態並查看聯合組織。

下表列出了每個控制台平台角色可以執行的操作。



== 組織管理角色

[cols="2,1,1"]
|===
| 任務 | 組織管理員 | 資料夾或專案管理員 


| 創建代理 | 是的 | 不 


| 從控制台建立、修改或刪除系統（新增或發現系統） | 是的 | 是的 


| 建立資料夾和項目，包括刪除 | 是的 | 不 


| 重新命名現有資料夾和項目 | 是的 | 是的 


| 分配角色並新增用戶 | 是的 | 是的 


| 將資源與資料夾和項目關聯 | 是的 | 是的 


| 將代理程式與資料夾和項目關聯 | 是的 | 不 


| 從資料夾和項目中刪除代理 | 是的 | 不 


| 管理代理程式（編輯證書、設定等） | 是的 | 不 


| 從管理 > 憑證管理憑證 | 是的 | 是的 


| 建立、管理和檢視聯合 | 是的 | 不 


| 透過控制台註冊支援並提交案例 | 是的 | 是的 


| 使用與明確存取角色無關的資料服務 | 是的 | 是的 


| 查看審核頁面和通知 | 是的 | 是的 
|===


== 聯盟角色

[cols="2,1,1"]
|===
| 任務 | 聯盟管理員 | 聯邦檢視器 


| 創建聯盟 | 是的 | 不 


| 驗證域名 | 是的 | 不 


| 將網域新增至聯合 | 是的 | 不 


| 禁用和刪除聯盟 | 是的 | 不 


| 測驗聯盟 | 是的 | 不 


| 查看聯盟及其詳細信息 | 是的 | 是的 
|===


== 合作夥伴角色

[cols="2,1,1"]
|===
| 任務 | 合作夥伴管理員 | 合作夥伴檢視器 


| 可以建立合作關係 | 是的 | 不 


| 為合作夥伴成員指派角色 | 是的 | 不 


| 可以為合作關係加入成員 | 是的 | 不 


| 可以查看組織合作關係詳細信息 | 是的 | 是的 
|===


== 超級管理員和查看者角色

*超級管理員*角色提供管理控制台功能、儲存和資料服務的完全存取權限。這個角色適合那些監督行政和治理的人。相較之下，「超級查看者」角色提供唯讀存取權限，非常適合需要查看資訊而不進行更改的審計員或利害關係人。

組織應謹慎使用*超級管理員*存取權限，以最大限度地降低安全風險並符合最小特權原則。大多數組織應該分配具有必要權限的細粒度角色，以降低風險並提高可審計性。

.超級角色範例
ABC 公司擁有一個由五人組成的小團隊，利用NetApp控制台進行資料服務和儲存管理。他們沒有分配多個角色，而是將「超級管理員」角色分配給兩名高階團隊成員，由他們負責所有管理任務，包括使用者管理和資源配置。其餘三名團隊成員被分配了*超級查看者*角色，允許他們監控儲存健康和數據服務狀態，但無法修改設定。

[cols="2,1"]
|===
| 角色 | 繼承的角色 


 a| 
超管理員
 a| 
* 組織管理員
* 資料夾或專案管理員
* 聯盟管理員
* 合作夥伴管理員
* 勒索軟體抵禦能力管理員
* 災難復原管理員
* 備份超級管理員
* 儲存管理員
* Keystone管理員
* Google Cloud NetApp Volumes管理員




 a| 
超觀眾
 a| 
* 組織檢視器
* 聯邦檢視器
* 合作夥伴檢視器
* 勒索軟體復原力檢視器
* 災難復原檢視器
* 備份檢視器
* 儲存檢視器
* Keystone檢視器
* Google Cloud NetApp Volumes檢視器


|===