---
sidebar: sidebar 
permalink: reference-limitations.html 
keywords: limitations, active directory, ad, iscsi, key managers, ip address, govcloud, Cloud Volumes ONTAP, days, running,  imdsv2, https tokens, Console agent 
summary: 已知限制標識了該產品的此版本不支援或無法與其正確互通的平台、裝置或功能。仔細審查這些限制。 
---
= NetApp Console的已知限制
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
已知限制標識了該產品的此版本不支援或無法與其正確互通的平台、裝置或功能。仔細審查這些限制。

這些限制是針對 NetApp Console 和管理設定的特定限制：代理程式、軟體即服務（SaaS）平台等等。



== 控制台代理限制



=== 可能與 172 範圍內的 IP 位址衝突

NetApp Console部署了一個具有兩個介面的代理，這兩個介面的 IP 位址分別在 172.17.0.0/16 和 172.18.0.0/16 範圍內。

如果您的網路具有配置了這些範圍之一的子網，那麼您可能會遇到控制台連線失敗的情況。例如，在控制台中發現本機ONTAP叢集可能會失敗。

請參閱知識庫文章link:https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Manager/Cloud_Manager_shows_inactive_as_Connector_IP_range_in_172.x.x.x_conflict_with_docker_network["代理IP與現有網路衝突"]有關如何變更代理介面的 IP 位址的說明。



=== 僅 Cloud Volumes ONTAP 支援 SSL 解密

僅支援與 Cloud Volumes ONTAP 關聯的代理使用透明代理伺服器。如果代理也與其他 NetApp 資料服務一起使用，則無法為其使用透明代理。如果您將 NetApp 資料服務與 Cloud Volumes ONTAP 搭配使用，請為 Cloud Volumes ONTAP 建立專用代理，以便使用透明代理伺服器。

為了增強安全性，您可以選擇link:task-installing-https-cert.html["安裝由憑證授權單位 (CA) 簽署的 HTTPS 憑證"]。



=== 載入本機 UI 時出現空白頁

如果您載入在代理程式上執行的基於 Web 的控制台，介面有時可能無法顯示，而只會顯示空白頁。

此問題與快取問題有關。解決方法是使用隱身或私人網路瀏覽器會話。



=== 不支援共享 Linux 主機

與其他應用程式共用的虛擬機器不支援該代理程式。  VM 必須專用於代理軟體。



=== 第三方代理和擴充程序

代理虛擬機器不支援第三方代理或虛擬機器擴充。
