---
sidebar: sidebar 
permalink: task-manage-user-credentials.html 
keywords: credentials, ontap credentials, update ontap credentials, update ontap password, nss account, nss credentials, nss login, nss password 
summary: '根據您在控制台中執行的操作，您可能已將ONTAP憑證和NetApp支援網站 (NSS) 憑證與您的使用者登入關聯。關聯這些憑證後，您可以檢視和管理它們。例如，如果您變更這些憑證的密碼，則需要在控制台中更新密碼。' 
---
= 管理與您的NetApp控制台登入關聯的憑證
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
根據您在控制台中執行的操作，您可能已將ONTAP憑證和NetApp支援網站 (NSS) 憑證與您的使用者登入關聯。關聯這些憑證後，您可以檢視和管理它們。例如，如果您變更這些憑證的密碼，則需要在控制台中更新密碼。



== ONTAP憑證

使用者需要ONTAP管理員憑證才能在控制台中發現ONTAP叢集。但是， ONTAP系統管理員存取取決於您是否使用控制台代理。

.無需控制台代理
系統會提示使用者輸入其ONTAP憑證以存取叢集的ONTAP系統管理員。使用者可以選擇將這些憑證保存在控制台中，這意味著他們不必每次都輸入這些憑證。使用者憑證僅對對應使用者可見，並且可以從使用者憑證頁面進行管理。

.使用控制台代理
預設情況下，不會提示使用者輸入其ONTAP憑證來存取ONTAP系統管理員。但是，控制台管理員（具有組織管理員角色）可以設定控制台以提示使用者輸入其ONTAP憑證。啟用此設定後，使用者每次都需要輸入其ONTAP憑證。

link:task-ontap-access-agent.html["了解更多。"^]



== NSS 憑證

與您的NetApp控制台登入關聯的 NSS 憑證可支援註冊、案例管理和存取Digital Advisor。

* 當您造訪*支援>資源*並註冊支援時，系統會提示您將 NSS 憑證與您的登入名稱關聯。
+
這將註冊您的組織或帳戶以獲得支持並啟動支持權利。您的組織中只有一個使用者必須將NetApp支援網站帳戶與其登入名稱關聯，以註冊支援並啟動支援權利。完成後，「*資源*」頁面將顯示您的帳戶已註冊支援。

+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-support-registration.html["了解如何註冊以獲得支持"^]

* 當您存取*管理 > 支援 > 案例管理*時，如果您還沒有輸入 NSS 憑證，系統會提示您輸入。此頁面使您能夠建立和管理與您的 NSS 帳戶和公司相關的支援案例。
* 當您在控制台中造訪Digital Advisor時，系統會提示您輸入 NSS 憑證登入Digital Advisor 。


請注意與您的登入名稱關聯的 NSS 帳戶的以下事項：

* 該帳戶在使用者層級進行管理，這意味著其他登入的使用者無法查看該帳戶。
* 每個使用者只能有一個與Digital Advisor和支援案例管理關聯的 NSS 帳戶。
* 如果您嘗試將NetApp支援網站帳號與Cloud Volumes ONTAP系統關聯，則只能從新增至您所屬組織的 NSS 帳戶中進行選擇。
+
NSS 帳戶級憑證與與您的登入關聯的 NSS 帳戶不同。  NSS 帳戶級憑證可讓您使用 BYOL 部署Cloud Volumes ONTAP 、註冊 PAYGO 系統並升級其軟體。

+
link:task-adding-nss-accounts.html["了解有關將 NSS 憑證與您的NetApp控制台組織或帳戶結合使用的更多信息"] 。





== 管理您的使用者憑證

透過更新使用者名稱和密碼或刪除憑證來管理您的使用者憑證。

.步驟
. 選擇“*管理 > 憑證*”。
. 選擇*使用者憑證*。
. 如果您還沒有任何使用者憑證，您可以選擇*新增 NSS 憑證*來新增您的NetApp支援網站帳戶。
. 透過從「操作」功能表中選擇以下選項來管理現有憑證：
+
** *更新憑證*：更新帳戶的使用者名稱和密碼。
** *刪除憑證*：刪除與您的控制台登入關聯的 NSS 帳戶。



