---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: '與您的 Active Directory 聯合驗證服務 (AD FS) 聯合，為NetApp控制台啟用單一登入 (SSO)。這允許用戶使用他們的公司憑證登入。' 
---
= 將NetApp控制台與 Active Directory 聯合服務 (AD FS) 聯合起來
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
將您的 Active Directory 聯合驗證服務 (AD FS) 與NetApp控制台聯合起來，以便為NetApp控制台啟用單一登入 (SSO)。這允許用戶使用他們的公司憑證登入控制台。

.必備角色
需要聯盟管理員角色來創建和管理聯盟。聯盟檢視者可以查看聯盟頁面。link:reference-iam-predefined-roles.html["了解有關訪問角色的更多資訊。"]


NOTE: 您可以與您的企業 IdP 或NetApp支援網站聯合。  NetApp建議選擇其中一個，但不要同時選擇兩者。

NetApp僅支援服務供應商發起的（SP發起的） SSO。首先，配置身分提供者以信任NetApp控制台作為服務提供者。然後，使用您的身分提供者的配置在控制台中建立連線。

您可以與 AD FS 伺服器建立聯合，以啟用NetApp控制台的單一登入 (SSO)。這個過程涉及配置您的 AD FS 以信任控制台作為服務提供者，然後在NetApp控制台中建立連線。

.開始之前
* 需要具有管理權限的 IdP 帳號。與您的 IdP 管理員協調以完成這些步驟。
* 確定要用於聯合的域。您可以使用您的電子郵件網域或您擁有的其他網域。如果您想要使用電子郵件網域以外的網域，則必須先在控制台中驗證該網域。您可以按照以下步驟操作link:task-federation-verify-domain.html["在NetApp控制台中驗證您的網域"]話題。


.步驟
. 選擇*管理>身分和存取*。
. 選擇“*Federation*”以查看“*Federations*”頁面。
. 選擇*配置新聯合*。
. 輸入您的網域詳細資料：
+
.. 選擇您是否要使用已驗證的網域或您的電子郵件網域。電子郵件網域是與您登入的帳戶關聯的網域。
.. 輸入您正在設定的聯盟的名稱。
.. 如果您選擇已驗證的網域，請從清單中選擇該網域。


. 選擇“下一步”。
. 對於您的連線方法，選擇*協定*，然後選擇*Active Directory 聯合驗證服務 (AD FS)*。
. 選擇“下一步”。
. 在您的 AD FS 伺服器中建立依賴方信任。您可以使用 PowerShell 或在 AD FS 伺服器上手動設定它。有關如何建立信賴方信任的詳細信息，請參閱 AD FS 文件。
+
.. 使用以下腳本透過 PowerShell 建立信任：
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. 或者，您可以在 AD FS 管理控制台中手動建立信任。建立信任時使用以下NetApp控制台值：
+
*** 建立依賴信任識別碼時，使用 **YOUR_TENANT** 值： `netapp-cloud-account`
*** 當您選擇 *啟用對 WS-Federation 的支援* 時，請使用 **YOUR_AUTH0_DOMAIN** 值： `netapp-cloud-account.auth0.com`


.. 建立信任後，從 AD FS 伺服器複製元資料 URL 或下載聯合元資料檔。您需要此 URL 或檔案來完成控制台中的連線。


+
NetApp建議使用元資料 URL 讓NetApp控制台自動擷取最新的 AD FS 設定。如果您下載聯合元資料文件，則每當 AD FS 配置發生變更時，都需要在NetApp控制台中手動更新它。

. 返回控制台，然後選擇「下一步」來建立連線。
. 建立與 AD FS 的連線。
+
.. 輸入您在上一個步驟中從 AD FS 伺服器複製的 *AD FS URL* 或上傳您從 AD FS 伺服器下載的聯合元資料檔案。


. 選擇*建立連線*。建立連線可能需要幾秒鐘。
. 選擇“下一步”。
. 選擇*測試連線*來測試您的連線。您將被引導至 IdP 伺服器的登入頁面。使用您的 IdP 憑證登入以完成測試並返回控制台以啟用連線。
. 選擇“下一步”。
. 在「啟用聯合」頁面上，查看聯合詳細信息，然後選擇「啟用聯合」。
. 選擇“*完成*”以完成該過程。


啟用聯合後，使用者可以使用其公司憑證登入NetApp控制台。
