---
sidebar: sidebar 
permalink: task-maintain-agents.html 
keywords: agent operating system, agent maintenance, vm maintenance, os updates, operating system updates, stop agent, restart agent, notifications, agent health, agent disk space, agent cpu usage, agent ram usage, agent vm, connector, connector health 
summary: 維護代理主機上的作業系統是您的責任。例如，您應該按照公司的作業系統分發標準程序，對控制台代理主機上的作業系統套用安全性更新。 
---
= 維護手動安裝的 Console 代理程式的 VM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
手動安裝 Console 代理程式時，維護代理主機上的作業系統是您（客戶）的責任。例如，您（客戶）應依照公司標準的作業系統分發流程，為代理主機上的作業系統套用安全性更新。



[[apply-operating-system-updates-to-the-agent-host]]
== 將作業系統更新套用至代理程式主機

無需停止代理主機服務即可套用作業系統安全性修補程式。

為了保持與支援組態的相容性、您應該防止 Docker 或 Podman 在例行作業系統修補期間升級。您可以在更新期間暫時排除 Docker 或 Podman 、或永久設定套件管理程式以跳過 Docker 或 Podman 更新、來執行此作業。

以下範例顯示如何在不同的 Linux 發行版中排除 Docker 或 Podman 更新。請查閱您的 Linux 發行版文件，以取得有關如何排除軟體套件更新的最新說明。

.Podman 範例
[source, bash]
----
sudo yum update --exclude=podman
sudo yum upgrade
----
.Docker 範例
[source, bash]
----
sudo apt-mark hold docker-ce docker-ce-cli containerd.io
sudo apt update
sudo apt upgrade
----


[[vm-or-instance-type]]
== VM 或實例類型

如果您從控制台建立控制台代理，它會使用預設配置在您的雲端提供者中部署 VM 執行個體。建立代理程式後，請勿切換到具有較少 CPU 或 RAM 的較小 VM 執行個體。

下表列出了 CPU 和 RAM 要求：

中央處理器:: 8 個核心或 8 個 vCPU
記憶體:: 32GB


link:reference-agent-default-config.html["了解代理的預設配置"] 。



[[monitor-the-agent]]
[[monitor-disk-space]]
== 監控代理

當代理虛擬機器不健康時，控制台會通知您，包括磁碟空間、RAM 和 CPU 問題。在控制台內的通知中心監控這些通知或設定電子郵件通知。磁碟空間、記憶體或 CPU 使用率偶爾增加是正常現象，但如果經常發生，則應採取措施解決。

例如，當代理資源（CPU、RAM 或磁碟空間）連續 30 分鐘超過其總容量的 90% 時，控制台會通知您。之後，如果資源使用率低於該閾值，則通知中心將顯示通知已解決（綠色）。


NOTE: 如果您對修改代理虛擬機器有任何疑問，請聯絡 NetApp 技術支援。

link:https://docs.netapp.com/us-en/console-setup-admin/task-monitor-cm-operations.html#notification-center["了解更多。"^]

[cols="47,47"]
|===
| 通知 | 需要採取行動 


| 磁碟空間過高 | link:https://kb.netapp.com/Cloud/BlueXP/Cloud_Manager/How_to_resolve_disk_space_issues_on_BlueXP_connector_VM["查看NetApp知識庫文章"^] 。 


| CPU 使用率過高 | 根據安裝位置，增加雲端提供者或本機代理程式 VM 的 CPU 大小。或者，建立額外的代理並將工作負載指派給多個代理程式。  RAM 利用率可能會因您的環境、 ONTAP工作負載、 Cloud Volumes ONTAP系統的數量以及您正在使用的資料服務而異。 


| RAM 使用率過高 | 根據安裝位置，增加雲端提供者或本地代理虛擬機器的 RAM。或者，建立額外的代理並將工作負載指派給多個代理程式。  RAM 利用率可能會因您的環境、 ONTAP工作負載、 Cloud Volumes ONTAP系統的數量以及您正在使用的資料服務而異。 
|===


[[stopping-and-starting-the-agent-vm]]
== 停止和啟動代理虛擬機

如果需要，請使用雲端提供者的控制台或標準內部部署程式停止並啟動代理虛擬機器。

link:concept-agents.html#agents-must-be-operational-at-all-times["請注意，控制台代理必須始終處於運行狀態"] 。



[[connect-to-the-linux-vm]]
[[connect-linux-host]]
== 連接 Linux VM

如果您需要連線到代理程式運行的 Linux VM，請使用雲端提供者提供的連線選項。

AWS:: 在 AWS 中建立代理執行個體時，請提供 AWS 存取金鑰和金鑰。您可以使用此金鑰對透過 SSH 連線到執行個體。對 EC2 Linux 執行個體使用使用者名稱「ubuntu」。對於 2023 年 5 月之前建立的代理，請使用使用者名稱「ec2-user」。
+
--
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AccessingInstances.html["AWS 文件：連接到您的 Linux 實例"^]

--
Azure:: 在 Azure 中建立代理程式 VM 時，您可以指定使用者名稱並選擇使用密碼或 SSH 公鑰進行驗證。使用您選擇的身份驗證方法連線到虛擬機器。
+
--
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/mac-create-ssh-keys#ssh-into-your-vm["Azure 文件：透過 SSH 進入您的虛擬機"^]

--
Google雲:: 在 Google Cloud 中建立代理程式時，您無法指定身份驗證方法。但是，您可以使用 Google Cloud Console 或 Google Cloud CLI (gcloud) 連線到 Linux VM 執行個體。
+
--
https://cloud.google.com/compute/docs/instances/connecting-to-instance["Google Cloud Docs：連接 Linux 虛擬機"^]

--

