---
sidebar: sidebar 
permalink: task-install-private-mode.html 
keywords: install dark site, deploy dark site, install private mode, deploy private mode, install agent dark site, agent dark site, dark site, private mode, no internet 
summary: 在私有模式下部署 NetApp Console，以便在沒有任何出站連線的情況下使用。首先，安裝 Console 代理程式，透過存取在 Console 代理程式上執行的使用者介面來設定 NetApp Console，然後提供您先前設定的雲端權限。 
---
= 以私有模式部署 Console 代理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在私有模式下部署 NetApp Console，以便在沒有任何出站連線的情況下使用。首先，安裝 Console 代理程式，透過存取在 Console 代理程式上執行的使用者介面來設定 NetApp Console，然後提供您先前設定的雲端權限。



== 步驟 1：安裝控制台代理

從 NetApp Support Site 下載產品安裝程式，然後手動將 Console 安裝到您自己的 Linux 主機上。

若要在 https://aws.amazon.com/federal/secret-cloud/["AWS Secret Cloud"^]或 https://aws.amazon.com/federal/top-secret-cloud/["AWS Top Secret Cloud"^]中使用 NetApp Console ，則應按照單獨的說明在這些環境中開始使用。 https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-getting-started-aws-c2s.html["了解如何在 AWS Secret Cloud 或 Top Secret Cloud 中開始使用 Cloud Volumes ONTAP"^]

.開始之前
* 安裝 Console 代理程式需要 root 權限。
* 根據您的作業系統，在安裝控制台代理之前需要 Podman 或 Docker Engine。


.步驟
. 從 NetApp Console 下載 Console 代理軟體 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp支援站點"^]
+
請務必下載離線安裝程式，以便在沒有網際網路存取的私人網路中使用。

. 將安裝程式複製到 Linux 主機。
. 分配運行腳本的權限。
+
[source, cli]
----
chmod +x /path/NetApp-Console-Private-Mode-<version>
----
+
其中 <version> 是您下載的控制台代理的版本。

. 運行安裝腳本：
+
[source, cli]
----
sudo /path/NetApp-Console-Private-Mode-<version>
----
+
其中 <version> 是您下載的控制台代理的版本。



.結果
Console 代理程式已安裝。現在您可以設定 NetApp Console 了。



== 第 2 步：設定NetApp Console

當您第一次存取 NetApp Console 時，系統會提示您設定 NetApp Console。

.步驟
. 開啟網頁瀏覽器，輸入安裝了 Console 代理程式的 Linux 主機的 IP 位址。
. 選擇 *Set Up New Console agent* ，然後按照提示設定系統。
+
** *系統詳情*：請輸入 Console 代理的名稱和公司名稱。
** *建立管理員使用者*：為系統建立管理員使用者。
** *檢閱*：檢閱詳細資料、接受授權合約，然後選取 *設定*。


. 使用您剛剛建立的 admin 使用者登入 NetApp Console。


.結果
Console 代理程式現已安裝。在網頁瀏覽器中存取其 IP 位址，以私密模式存取 NetApp Console。

當有新版 Console 軟體可用時，將會發布在 NetApp 支援網站。link:task-upgrade-agent.html["了解如何升級 Console 代理程式"]。

.下一步是什麼？
向 Console 代理程式提供您先前設定的雲端供應商權限。



== 步驟 3：向 Console 代理程式授予權限

如果要建立 Cloud Volumes ONTAP 工作環境，則需要向 Console 代理提供您先前設定的雲端供應商權限。

link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions["了解如何準備雲端權限"]。

[role="tabbed-block"]
====
.AWS IAM 角色
--
將您先前建立的 IAM 角色附加到 Console 代理 EC2 執行個體。

.步驟
. 前往 Amazon EC2 主控台。
. 選擇*實例*。
. 選擇控制台代理實例。
. 選擇*操作>安全性>修改 IAM 角色*。
. 選擇 IAM 角色並選擇 *更新 IAM 角色*。


--
.AWS 存取金鑰
--
向 Console 代理提供具有所需權限的 IAM 使用者的 AWS 存取金鑰。

.步驟
. 選擇“*管理 > 憑證*”。
. 選擇*組織憑證*。
. 選擇“*新增憑證*”並按照精靈中的步驟操作。
+
.. *憑證位置*：選擇*Amazon Web Services > 代理程式。
.. *定義憑證*：輸入 AWS 存取金鑰和金鑰。
.. *市場訂閱*：透過立即訂閱或選擇現有訂閱將市場訂閱與這些憑證關聯。
.. *審核*：確認有關新憑證的詳細資訊並選擇*新增*。




--
.Azure 角色
--
前往 Azure 入口網站並將 Azure 自訂角色指派給一個或多個訂閱的控制台代理虛擬機器。

.步驟
. 從 Azure 入口網站開啟「*訂閱*」服務並選擇您的訂閱。
+
從*訂閱*服務分配角色很重要，因為這指定了訂閱等級的角色分配範圍。 _範圍_定義了存取適用的資源集。如果您在不同層級（例如，虛擬機器層級）指定範圍，則您在NetApp Console內完成操作的能力將受到影響。

+
https://learn.microsoft.com/en-us/azure/role-based-access-control/scope-overview["Microsoft Azure 文件：了解 Azure RBAC 的範圍"^]

. 選擇*存取控制 (IAM)* > *新增* > *新增角色分配*。
. 在*角色*標籤中，選擇*控制台操作員*角色並選擇*下一步*。
+

NOTE: 控制台操作員是策略中提供的預設名稱。如果您為角色選擇了不同的名稱，請選擇該名稱。

. 在「*成員*」標籤中，完成以下步驟：
+
.. 指派對*託管身分*的存取權限。
.. 選擇“選擇成員”，選擇建立控制台代理虛擬機器的訂閱，在“託管識別”下，選擇“虛擬機器”，然後選擇控制台代理虛擬機器。
.. 選擇*選擇*。
.. 選擇“下一步”。
.. 選擇*審閱+分配*。
.. 如果要管理其他 Azure 訂閱中的資源，請切換到該訂閱，然後重複這些步驟。




--
.Azure 服務主體
--
請將您先前設定的 Azure 服務主體的憑證提供給 Console 代理程式。

.步驟
. 選擇“*管理 > 憑證*”。
. 選擇“*新增憑證*”並按照精靈中的步驟操作。
+
.. *憑證位置*：選擇*Microsoft Azure > 代理程式*。
.. *定義憑證*：輸入有關授予所需權限的 Microsoft Entra 服務主體的資訊：
+
*** 應用程式（客戶端）ID
*** 目錄（租戶）ID
*** 客戶端密鑰


.. *市場訂閱*：透過立即訂閱或選擇現有訂閱將市場訂閱與這些憑證關聯。
.. *審核*：確認有關新憑證的詳細資訊並選擇*新增*。




--
.Google Cloud 服務帳號
--
將服務帳戶與控制台代理 VM 關聯。

.步驟
. 前往 Google Cloud 入口網站並將服務帳戶指派給控制台代理程式 VM 執行個體。
+
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#changeserviceaccountandscopes["Google Cloud 文件：變更執行個體的服務帳戶和存取範圍"^]

. 如果您想管理其他專案中的資源，請透過將具有控制台代理角色的服務帳戶新增至該專案來授予存取權限。您需要對每個項目重複此步驟。


--
====