---
sidebar: sidebar 
permalink: task-federation-adfs.html 
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity 
summary: '與您的 Active Directory 聯合驗證服務 (AD FS) 聯合，為NetApp Console啟用單一登入 (SSO)。這允許用戶使用他們的公司憑證登入。' 
---
= 將 NetApp Console 與 Active Directory Federation Services 建立聯盟
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
將您的 Active Directory 聯合驗證服務 (AD FS) 與NetApp Console聯合起來，以便為NetApp Console啟用單一登入 (SSO)。這允許用戶使用他們的公司憑證登入控制台。

.必備角色
建立和管理聯盟需要 Federation 管理員角色。Federation 檢視者可以檢視 Federation 頁面。link:reference-iam-predefined-roles.html["了解有關訪問角色的更多資訊。"]


NOTE: 您可以與您的企業 IdP 或NetApp支援網站聯合。  NetApp建議選擇其中一個，但不要同時選擇兩者。

NetApp僅支援服務供應商發起的（SP發起的） SSO。首先，配置身分提供者以信任NetApp Console作為服務提供者。然後，使用您的身分提供者的配置在控制台中建立連線。

您可以與您的 AD FS 伺服器設定聯盟，以啟用 NetApp Console 的單一登入（SSO）。此流程包括將您的 AD FS 設定為信任 Console 作為服務提供者，然後在 NetApp Console 中建立連線。

.開始之前
* 需要具有管理權限的 IdP 帳號。與您的 IdP 管理員協調以完成這些步驟。
* 識別您要用於聯合的網域。您可以使用您的電子郵件網域或您擁有的其他網域。如果您想使用電子郵件網域以外的網域，則必須先在 NetApp Console 中驗證該網域。如需相關指示，請參閱 link:task-federation-verify-domain.html["在NetApp Console中驗證您的網域"]。


.步驟
. 選擇*管理>身分和存取*。
. 選擇“*Federation*”以查看“*Federations*”頁面。
. 選擇*配置新聯合*。
. 輸入您的網域詳細資料：
+
.. 選擇您是否要使用已驗證的網域或您的電子郵件網域。電子郵件網域是與您登入的帳戶關聯的網域。
.. 輸入您正在設定的聯盟的名稱。
.. 如果您選擇已驗證的網域，請從清單中選擇該網域。


. 選擇“下一步”。
. 對於您的連線方法，選擇*協定*，然後選擇*Active Directory 聯合驗證服務 (AD FS)*。
. 選擇“下一步”。
. 在您的 AD FS 伺服器中建立依賴方信任。您可以使用 PowerShell 或在 AD FS 伺服器上手動設定它。有關如何建立信賴方信任的詳細信息，請參閱 AD FS 文件。
+
.. 使用 PowerShell 執行以下腳本以建立信任關係：
+
[source, powershell]
----
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"
----
.. 或者，您可以在 AD FS 管理控制台中手動建立信任。建立信任時使用以下NetApp Console值：
+
*** 建立 Relying Trust Identifier 時、請使用 *YOUR_TENANT* 值： `netapp-cloud-account`
*** 選擇 *Enable support for the WS-Federation* 時，請使用 *YOUR_AUTH0_DOMAIN* 值： `netapp-cloud-account.auth0.com`


.. 建立信任後，從 AD FS 伺服器複製元資料 URL 或下載聯合元資料檔。您需要此 URL 或檔案來完成控制台中的連線。


+
NetApp建議使用元資料 URL 讓NetApp Console自動擷取最新的 AD FS 設定。如果您下載聯合元資料文件，則每當 AD FS 配置發生變更時，都需要在NetApp Console中手動更新它。

. 返回控制台，然後選擇「下一步」來建立連線。
. 建立與 AD FS 的連線。
+
.. 輸入您在上一個步驟中從 AD FS 伺服器複製的 *AD FS URL* 或上傳您從 AD FS 伺服器下載的聯合元資料檔案。


. 選擇*建立連線*。建立連線可能需要幾秒鐘。
. 選擇“下一步”。
. 選擇*測試連線*來測試您的連線。您將被引導至 IdP 伺服器的登入頁面。使用您的身分提供者憑證登入。登入後，返回控制台啟用連線。
+

NOTE: 在受限模式下使用控制台時，請將 URL 複製到隱身瀏覽器視窗或單獨的瀏覽器中，以登入您的身分提供者 (IdP)。

. 在控制台中，選擇「下一步」以查看摘要頁面。
. 設定通知。
+
選擇 7 天或 30 天。系統會透過電子郵件向具有以下角色的任何使用者發送到期通知，並在 NetApp Console 中顯示這些通知：超級管理員、組織管理員、聯盟管理員和聯盟檢視者。

. 查看聯盟詳細信息，然後選擇“啟用聯盟”。
. 選擇“*完成*”以完成該過程。


啟用聯合身份驗證後，使用者可以使用其企業憑證登入NetApp Console。
