---
sidebar: sidebar 
permalink: task-uninstall-agent.html 
keywords: uninstall, remove connector, uninstall connector, uninstall agent, remove agent 
summary: 解除安裝 Console 代理程式以疑難排解問題、或從主機永久移除代理程式。您需要使用的步驟取決於您使用的部署模式。從環境中移除 Console 代理程式後、您可以從 Console 中將其移除。 
---
= 解除安裝並移除 NetApp Console 代理程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
解除安裝 Console 代理程式以疑難排解問題、或從主機永久移除代理程式。您需要使用的步驟取決於您使用的部署模式。從環境中移除 Console 代理程式後、您可以從 Console 中將其移除。



[[uninstall-the-agent-when-it-has-outbound-connectivity]]
== 當代理程式具有出站連線能力時，請將其解除安裝

如果您使用的是標準模式或受限模式（換句話說，代理主機具有出站連線），那麼您應該按照下列步驟卸載代理程式。

.步驟
. 連接到代理程式的 Linux VM。
. 從 Linux 主機執行卸載腳本：
+
`/opt/application/netapp/service-manager-2/uninstall.sh [silent]`

+
_silent_ 運行腳本而不提示您確認。





[[uninstall-the-agent-when-it-has-no-outbound-connectivity]]
== 當代理程式沒有出站連線時、請卸載該代理程式

如果您的代理程式沒有出站連線（例如，在私有模式下），則必須手動從主機中移除代理軟體。

.步
. 連接到控制台代理的 Linux VM。
. 在 Linux 主機上，執行以下命令：
+
[source, cli]
----
/opt/application/netapp/ds/cleanup.sh
rm -rf /opt/application/netapp/
----
. 在 Linux 主機上，刪除舊的、未使用的容器映像檔，以釋放 /var 目錄中的空間進行重新安裝。
+
[role="tabbed-block"]
====
.Podman
--
[source, cli]
----
podman system prune --all
----
--
.Docker
--
[source, cli]
----
docker system prune -a
----
--
====




[[remove-console-agents-from-the-console]]
== 從控制台中刪除控制台代理

如果您刪除了代理虛擬機器或卸載了代理，則應將其從控制台的代理清單中刪除。刪除代理虛擬機器或卸載代理軟體後，代理程式在控制台中顯示狀態為「已中斷連線」。

刪除控制台代理程式時請注意以下事項：

* 此操作不會刪除虛擬機器。
* 此操作無法恢復 - 一旦刪除控制台代理，就無法將其加回。


.步驟
. 選擇“*管理 > 代理*”。
. 在 *Overview* 頁面上，選擇已中斷連線的代理程式的操作選單，然後選擇 *Remove agent* 。
. 輸入代理人的姓名進行確認，然後選擇*刪除*。

