---
sidebar: sidebar 
permalink: task-configuring-proxy.html 
keywords: proxy, proxy server, proxy, internet, HTTP, http, https, bluexp 
summary: 如果您的公司政策要求您使用代理伺服器進行所有與互聯網的通信，那麼您需要設定您的代理以使用該代理伺服器。如果您在安裝期間沒有將控制台代理程式設定為使用代理伺服器，那麼您可以隨時將控制台代理程式設定為使用該代理伺服器。 
---
= 配置控制台代理以使用代理伺服器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您的公司政策要求您使用代理伺服器進行所有與互聯網的通信，那麼您需要設定您的代理以使用該代理伺服器。如果您在安裝期間沒有將控制台代理程式設定為使用代理伺服器，那麼您可以隨時將控制台代理程式設定為使用該代理伺服器。

代理程式的代理伺服器無需公用 IP 或 NAT 閘道即可實現出站網際網路存取。代理伺服器僅為控制台代理提供出站連接，而不為Cloud Volumes ONTAP系統提供出站連接。

如果Cloud Volumes ONTAP系統缺少出站互聯網訪問，控制台會將其配置為使用控制台代理的代理伺服器。您必須確保控制台代理程式的安全群組允許透過連接埠 3128 進行入站連線。部署控制台代理程式後開啟此連接埠。

如果控制台代理本身沒有出站互聯網連接， Cloud Volumes ONTAP系統將無法使用已設定的代理伺服器。



== 支援的配置

* 為Cloud Volumes ONTAP系統提供服務的代理支援透明代理伺服器。如果您將NetApp資料服務與Cloud Volumes ONTAP一起使用，請為Cloud Volumes ONTAP建立專用代理，您可以在其中使用透明代理伺服器。
* 所有代理程式都支援明確代理伺服器，包括管理Cloud Volumes ONTAP系統的代理程式和管理NetApp資料服務的代理程式。
* HTTP 和 HTTPS。
* 代理伺服器可以位於雲端或您的網路。



IMPORTANT: 一旦配置了代理，您就無法變更代理類型。如果需要變更代理類型，請刪除控制台代理並新增具有新代理類型的新代理程式。



== 在控制台代理上啟用明確代理

當您將控制台代理程式設定為使用代理伺服器時，該代理程式及其管理的Cloud Volumes ONTAP系統（包括任何 HA 中介）都會使用代理伺服器。

此操作重新啟動控制台代理程式。在繼續之前，請先確認控制台代理是否空閒。

.步驟
. 選擇“*管理 > 代理*”。
. 在*概覽*頁面上，選擇控制台代理程式的操作選單，然後選擇*編輯代理*。
+
控制台代理程式必須處於活動狀態才能對其進行編輯。

. 選擇*HTTP代理配置*。
. 在配置類型欄位中選擇*明確代理*。
. 選擇*啟用代理*。
. 使用語法指定伺服器 http://_address:port_[]或者 https://_address:port_[]
. 如果伺服器需要基本驗證，請指定使用者名稱和密碼。
+
請注意以下事項：

+
** 使用者可以是本機使用者或網域使用者。
** 對於網域用戶，您必須輸入 \ 的 ASCII 代碼，如下所示：domain-name%92user-name
+
例如：netapp%92proxy

** 控制台不支援包含 @ 字元的密碼。


. 選擇*儲存*。




== 為控制台代理啟用透明代理

僅Cloud Volumes ONTAP支援在控制台代理上使用透明代理。如果您除了Cloud Volumes ONTAP之外還使用NetApp資料服務，則應建立一個單獨的代理來用於資料服務或用於Cloud Volumes ONTAP。

啟用透明代理前，請確保滿足以下要求：

* 代理與透明代理伺服器安裝在同一網路上。
* 代理伺服器上啟用了 TLS 檢查。
* 您有一個 PEM 格式的證書，與透明代理伺服器上使用的證書相符。
* 您不要將控制台代理用於除Cloud Volumes ONTAP之外的任何NetApp資料服務。


若要將現有代理程式設定為使用透明代理伺服器，請使用可透過控制台代理主機上的命令列取得的控制台代理維護工具。

當您設定代理伺服器時，控制台代理將重新啟動。在繼續之前，請先確認控制台代理是否空閒。

.步驟
確保您擁有代理伺服器的 PEM 格式的憑證檔案。如果您沒有證書，請聯絡您的網路管理員以取得證書。

. 在控制台代理主機上開啟命令列介面。
. 導覽至控制台代理維護工具目錄： `/opt/application/netapp/service-manager-2/agent-maint-console`
. 運行以下命令啟用透明代理，其中 `/home/ubuntu/<certificate-file>.pem`是您擁有的代理伺服器憑證檔案的目錄和名稱：
+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----
+
確保證書檔案為 PEM 格式並與命令位於同一目錄中，或指定證書檔案的完整路徑。

+
[source, CLI]
----
./agent-maint-console proxy add -c /home/ubuntu/<certificate-file>.pem
----




=== 修改控制台代理的透明代理

您可以使用 `proxy update`命令或使用 `proxy remove`命令。有關詳細信息，請參閱link:reference-agent-maint-console.html["代理維護控制台"]。


IMPORTANT: 一旦配置了代理，您就無法變更代理類型。如果需要變更代理類型，請刪除控制台代理並新增具有新代理類型的新代理程式。



== 如果控制台代理無法存取互聯網，請更新它

如果您的網路代理程式配置發生變化，您的代理程式可能會失去對網際網路的存取權限。例如，如果有人更改了代理伺服器的密碼或更新了憑證。在這種情況下，您需要直接從控制台代理主機存取 UI 並更新設定。確保您可以透過網路存取控制台代理主機，並且可以登入控制台。



== 啟用直接 API 流量

如果您將控制台代理程式設定為使用代理伺服器，則可以在控制台代理程式上啟用直接 API 流量，以便將 API 呼叫直接傳送至雲端提供者服務，而無需透過代理程式。在 AWS、Azure 或 Google Cloud 中執行的代理程式支援此選項。

如果您停用帶有Cloud Volumes ONTAP 的Azure Private Links 並使用服務端點，請啟用直接 API 流量。否則，流量將無法正確路由。

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html["了解有關將 Azure Private Link 或服務端點與Cloud Volumes ONTAP結合使用的更多信息"^]

.步驟
. 選擇“*管理 > 代理*”。
. 在*概覽*頁面上，選擇控制台代理程式的操作選單，然後選擇*編輯代理*。
+
控制台代理程式必須處於活動狀態才能對其進行編輯。

. 選擇*支援直接 API 流量*。
. 選取核取方塊以啟用該選項，然後選擇*儲存*。

