= BlueXP身分與存取管理
:allow-uri-read: 




=== BlueXP身分與存取管理

BlueXP身分和存取管理 (IAM) 是一種新的資源和存取管理模型，它取代並增強了在標準模式下使用BlueXP時BlueXP帳戶提供的先前功能。

BlueXP IAM 提供更精細的資源和權限管理：

* 頂級_組織_使您能夠管理各個_項目_的存取權限。
* _資料夾_使您能夠將相關項目分組在一起。
* 增強的資源管理可讓您將資源與一個或多個資料夾或項目關聯。
+
例如，您可以將一個Cloud Volumes ONTAP系統與多個項目關聯。

* 增強的存取管理可讓您為組織層次結構不同層級的成員指派角色。


這些增強功能可以更好地控制使用者可以執行的操作和可以存取的資源。

.BlueXP IAM 如何影響您的現有帳戶
當您登入BlueXP時，您會注意到以下變化：

* 您的_帳戶_現在稱為_組織_
* 您的_工作區_現在稱為_項目_
* 使用者角色的名稱已更改：
+
** _帳號管理員_ 現為 _組織管理員_
** _工作區管理員_現在是_資料夾或專案管理員_
** _合規性檢視器_現為_分類檢視器_


* 在「設定」下，您可以存取BlueXP身分和存取管理以利用這些增強功能


請注意以下事項：

* 您的現有使用者或工作環境沒​​有任何變更。
* 雖然角色的名稱已經改變，但從權限的角度來看並沒有什麼不同。使用者將繼續可以存取與以前相同的工作環境。
* 您登入BlueXP的方式沒有任何變化。  BlueXP IAM 與NetApp雲端登入、 NetApp支援網站憑證和聯合連線搭配使用，就像BlueXP帳號一樣。
* 如果您有多個BlueXP帳戶，那麼您現在就有多個BlueXP組織。


.BlueXP IAM 的 API
此變更為BlueXP IAM 引入了一個新的 API，但它與先前的租賃 API 向後相容。 https://docs.netapp.com/us-en/console-automation/tenancyv4/overview.html["了解BlueXP IAM 的 API"^]

.支援的部署模式
在標準模式下使用BlueXP時支援BlueXP IAM。如果您在受限模式或私人模式下使用BlueXP ，那麼您將繼續使用BlueXP _帳戶_來管理工作區、使用者和資源。

.下一步
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-identity-and-access-management.html["了解BlueXP IAM"]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-get-started.html["開始使用BlueXP IAM"]




=== 連接器 3.9.45

此版本包括擴展的作業系統支援和錯誤修復。

3.9.45 版本適用於標準模式和限制模式。

.支援 Ubuntu 24.04 LTS
從 3.9.45 版本開始， BlueXP現在支援在標準模式或受限模式下使用BlueXP時在 Ubuntu 24.04 LTS 主機上新安裝 Connector。

https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html#step-1-review-host-requirements["查看連接器主機需求"] 。



=== RHEL 主機支援 SELinux

BlueXP現在支援在強制模式或授權模式下啟用 SELinux 的 Red Hat Enterprise Linux 主機的連接器。

從 3.9.40 版本開始支援標準模式和限制模式，從 3.9.42 版本開始支援私有模式。

請注意以下限制：

* BlueXP不支援 Ubuntu 主機的 SELinux。
* 作業系統上啟用了 SELinux 的連接器不支援對Cloud Volumes ONTAP系統的管理。


https://docs.redhat.com/en/documentation/red_hat_enterprise_linux/8/html/using_selinux/getting-started-with-selinux_using-selinux["了解有關 SELinux 的更多信息"^]
