= 連接器 3.9.52
:allow-uri-read: 




=== 連接器 3.9.52

BlueXP Connector 的此版本包括一些小的安全性改進和錯誤修復，以及一些額外的更新。

目前，3.9.52 版本適用於標準模式和限制模式。



==== 支援 Docker 27 和 Docker 28

連接器現在支援 Docker 27 和 Docker 28。



==== Cloud Volumes ONTAP

當連接器不合規或停機超過 14 天時， Cloud Volumes ONTAP節點不再關閉。當Cloud Volumes ONTAP失去對連接器的存取權時，它仍會發送事件管理訊息。此變更是為了確保即使連接器長時間處於關閉狀態， Cloud Volumes ONTAP仍可繼續運作。它不會改變連接器的合規性要求。



=== BlueXP中提供Keystone管理

BlueXP中的NetApp Keystone測試版增加了對Keystone管理的存取權。您可以從BlueXP左側導覽列存取NetApp Keystone測試版的註冊頁面。



=== BlueXP身分和存取管理 (IAM)



==== 新的儲存管理角色

儲存管理員、系統健康專家和儲存檢視器角色可用，可以指派給使用者。

這些角色使您能夠管理組織中的誰可以發現和管理儲存資源，以及查看儲存健康資訊和執行軟體更新。

這些角色支援控制對以下儲存資源的存取：

* E系列系統
* StorageGRID系統
* 本地ONTAP系統


您也可以使用這些角色來控制對以下BlueXP服務的存取：

* 軟體更新
* 數位顧問
* 營運彈性
* 經濟效益
* 永續性


已新增以下角色：

* *存儲管理員*
+
管理組織內儲存資源的儲存健康、治理和發現。該角色還可以對儲存資源執行軟體更新。

* *系統健康專家*
+
管理組織內儲存資源的儲存健康和治理。該角色還可以對儲存資源執行軟體更新。此角色不能修改或刪除工作環境。

* *儲存檢視器*
+
查看儲存健康資訊和治理資料。

+
link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["了解訪問角色。"^]


