= 
:allow-uri-read: 


.開始之前
您應該具有以下內容：

* 安裝代理程式的 root 權限。
* 如果代理需要代理才能存取互聯網，則提供有關代理伺服器的詳細資訊。
+
您可以選擇在安裝後設定代理伺服器，但這樣做需要重新啟動代理。

* 如果代理伺服器使用 HTTPS 或代理是攔截代理，則需要 CA 簽署的憑證。


.關於此任務
NetApp支援網站上提供的安裝程式可能是早期版本。安裝後，如果有新版本可用，代理程式會自動更新。

.步驟
. 如果主機上設定了 _http_proxy_ 或 _https_proxy_ 系統變量，請將其刪除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不刪除這些系統變量，安裝將會失敗。

. 從下載代理軟體 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp支援站點"^]，然後將其複製到Linux主機上。
+
您應該下載適用於您的網路或雲端中的「線上」代理安裝程式。

. 分配運行腳本的權限。
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
其中 <version> 是您下載的代理程式的版本。

. 運行安裝腳本。
+
[source, cli]
----
 ./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>
----
+
--proxy 和 --cacert 參數是可選的。如果您有代理伺服器，則需要輸入所示的參數。安裝程式不會提示您提供有關代理的資訊。

+
以下是使用兩個可選參數的命令範例：

+
[source, cli]
----
 ./NetApp-Console-Agent-v4.0.0--proxy https://user:password@10.0.0.30:8080/ --cacert /tmp/cacert/certificate.cer
----
+
--proxy 使用下列格式之一將代理程式設定為使用 HTTP 或 HTTPS 代理伺服器：

+
** \http://位址:埠
** \http://用戶名:密碼@地址:端口
** \http://網域%92用戶名:密碼@位址:端口
** \https://位址:埠
** \https://使用者名稱:密碼@位址:端口
** \https://網域%92用戶名:密碼@地址:端口
+
請注意以下事項：

+
*** 使用者可以是本機使用者或網域使用者。
*** 對於網域用戶，您必須使用 \ 的 ASCII 代碼，如上所示。
*** 此代理程式不支援包含 @ 字元的使用者名稱或密碼。
*** 如果密碼包含以下任何特殊字符，則必須在該特殊字符前面加上反斜杠來轉義該特殊字符：& 或 !
+
例如：

+
\http://bxpproxyuser:netapp1\!@網址:3128





+
--cacert 指定用於代理程式和代理伺服器之間的 HTTPS 存取的 CA 簽章憑證。僅當您指定 HTTPS 代理伺服器或代理程式是攔截代理時才需要此參數。

. 如果您使用 Podman，則需要調整 aardvark-dns 連接埠。
+
.. 透過 SSH 連接到代理虛擬機器。
.. 開啟 podman _/usr/share/containers/containers.conf_ 檔案並修改 Aardvark DNS 服務的選定連接埠。例如，將其更改為54。
+
[source, cli]
----
vi /usr/share/containers/containers.conf
...
# Port to use for dns forwarding daemon with netavark in rootful bridge
# mode and dns enabled.
# Using an alternate port might be useful if other DNS services should
# run on the machine.
#
dns_bind_port = 54
...
Esc:wq
----
.. 重新啟動代理虛擬機器。




. 等待安裝完成。
+
安裝結束時，如果您指定了代理伺服器，代理服務（occm）將重新啟動兩次。

. 從與代理虛擬機器有連線的主機開啟 Web 瀏覽器並輸入以下 URL：
+
https://_ipaddress_[]

. 登入後，設定代理：
+
.. 指定與代理程式關聯的控制台組織。
.. 輸入系統的名稱。
.. 在*您是否在安全環境中運作？ *下保持限制模式為停用。
+
您應該保持限制模式處於停用狀態，因為這些步驟描述如何在標準模式下使用控制台。只有當您擁有安全的環境並希望中斷此帳戶與控制台後端服務的連線時，才應啟用受限模式。如果真是這樣的話，link:task-quick-start-restricted-mode.html["依照步驟在受限模式下開始使用NetApp Console"] 。

.. 選擇*讓我們開始吧*。



