= 在根橋接中使用 NetAvark 時，用於 DNS 轉送守護程序的連接埠
:allow-uri-read: 


.開始之前
您應該具有以下內容：

* 安裝控制台代理程式的 root 權限。
* 如果控制台代理需要代理才能存取互聯網，則提供有關代理伺服器的詳細資訊。
+
您可以選擇在安裝後設定代理伺服器，但這樣做需要重新啟動控制台代理。

* 如果代理伺服器使用 HTTPS 或代理是攔截代理，則需要 CA 簽署的憑證。



NOTE: 手動安裝控制台代理程式時，無法為透明代理伺服器設定憑證。如果需要為透明代理伺服器設定證書，則必須在安裝後使用維護控制台。詳細了解link:reference-connector-maint-console.html["代理維護控制台"]。

.關於此任務
NetApp支援網站上提供的安裝程式可能是早期版本。安裝後，如果有新版本可用，控制台代理會自動更新。

.步驟
. 如果主機上設定了 _http_proxy_ 或 _https_proxy_ 系統變量，請將其刪除：
+
[source, cli]
----
unset http_proxy
unset https_proxy
----
+
如果不刪除這些系統變量，安裝將會失敗。

. 從下載控制台代理軟體 https://mysupport.netapp.com/site/products/all/details/cloud-manager/downloads-tab["NetApp支援站點"^]，然後將其複製到Linux主機上。
+
您應該下載適用於您的網路或雲端中的「線上」代理安裝程式。

. 分配運行腳本的權限。
+
[source, cli]
----
chmod +x NetApp-Console-Agent-<version>
----
+
其中 <version> 是您下載的控制台代理的版本。

. 運行安裝腳本。
+
[source, cli]
----
./NetApp-Console-Agent-<version> --proxy <HTTP or HTTPS proxy server> --cacert <path and file name of a CA-signed certificate>

+
You'll need to add proxy information if your network requires a proxy for internet access. You can add either a transparent or explicit proxy. The --proxy and --cacert parameters are optional and you won't be prompted to add them. If you have a proxy server, you will need to enter the parameters as shown.
+
Here is an example configuring an explicit proxy server with a CA-signed certificate:
+
[source,cli]
----


[listing]
----
+
--proxy configures the Console agent to use an HTTP or HTTPS proxy server using one of the following formats:
+
* \http://address:port
* \http://user-name:password@address:port
* \http://domain-name%92user-name:password@address:port
* \https://address:port
* \https://user-name:password@address:port
* \https://domain-name%92user-name:password@address:port
+
Note the following:
+
** The user can be a local user or domain user.
** For a domain user, you must use the ASCII code for a \ as shown above.
** The Console agent doesn't support user names or passwords that include the @ character.
** If the password includes any of the following special characters, you must escape that special character by prepending it with a backslash: & or !
+
For example:
+
\http://bxpproxyuser:netapp1\!@address:3128

+
--cacert specifies a CA-signed certificate to use for HTTPS access between Console agent and the proxy server. This parameter is required for HTTPS proxy servers, intercepting proxy servers, and transparent proxy servers.

+
Here is an example configuring a transparent proxy server. When you configure a transparent proxy, you don't need to define the proxy server. You only add a CA-signed certificate to your Console agent host:

+
[source,cli]
----
 ./NetApp-Console-Agent-v4.0.0 --cacert /tmp/cacert/certificate.cer
[listing]
----
. If you used Podman, you'll need to adjust the aardvark-dns port.
.. SSH to the Console agent virtual machine.
.. Open podman _/usr/share/containers/containers.conf_ file and modify the chosen port for Aardvark DNS service. For example, change it to 54.
+
[source, cli]
----
vi /usr/share/containers/containers.conf

[listing]
----
+
For example:
+
[source,text]
----


= 在根橋接中使用 NetAvark 時，用於 DNS 轉送守護程序的連接埠



= 模式和 DNS 已啟用。



= 如果其他 DNS 服務需要使用備用端口，使用備用端口可能很有用。



= 在機器上運行。

# dns_bind_port = 54

[listing]
----
.. Reboot the Console agent virtual machine.
//end::main-steps[]

//tag::standard-mode-steps-for-cloud[]
. Wait for the installation to complete.
+
At the end of the installation, the Console agent service (occm) restarts twice if you specified a proxy server.

. Open a web browser from a host that has a connection to the Console agent virtual machine and enter the following URL:
+
https://_ipaddress_

. After you log in, set up the Console agent:
.. Specify the organization to associate with the Console agent.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
You should keep restricted mode disabled because these steps describe how to use the Console in standard mode. You should enable restricted mode only if you have a secure environment and want to disconnect this account from backend services. If that's the case, link:task-quick-start-restricted-mode.html[follow steps to get started with the NetApp Console in restricted mode].
.. Select *Let's start*.

//end::standard-mode-steps-for-cloud[]
----